networks:
  bdnr-cassandra-net:

services:
  cassandra:
    image: cassandra
    container_name: bdnr-cassandra
    ports:
      - "9042:9042"
    environment:
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=100M
    volumes:
      - ./cassandra-data:/var/lib/cassandra
    networks:
      - bdnr-cassandra-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "describe keyspaces"]
      interval: 30s
      timeout: 10s
      retries: 5

  flask-app:
    build: ./app
    container_name: flask-app
    ports:
      - "5000:5000"
    depends_on:
      cassandra:
        condition: service_healthy
    networks:
      - bdnr-cassandra-net
    volumes:
      - ./app:/app
