export const COMPONENTS = [
    {
        title: 'Case Accessories',
        href: '/products?category=case-accessory',
        description: 'Additional parts and accessories for PC cases',
        icon: 'Tool',
    },
    {
        title: 'Case Fans',
        href: '/products?category=case-fan',
        description: 'Cooling fans for optimal PC case airflow',
        icon: 'Fan',
    },
    {
        title: 'Cases',
        href: '/products?category=case',
        description: 'PC enclosures and chassis for your build',
        icon: 'Box',
    },
    {
        title: 'CPUs',
        href: '/products?category=cpu',
        description: 'Central processing units for your PC',
        icon: 'Cpu',
    },
    {
        title: 'CPU Coolers',
        href: '/products?category=cpu-cooler',
        description: 'Cooling solutions for your processor',
        icon: 'Snowflake',
    },
    {
        title: 'External Hard Drives',
        href: '/products?category=external-hard-drive',
        description: 'Portable storage solutions for data backup and transfer',
        icon: 'HardDrive',
    },
    {
        title: 'Fan Controllers',
        href: '/products?category=fan-controller',
        description: 'Devices to manage and control case fan speeds',
        icon: 'Settings',
    },
    {
        title: 'Headphones',
        href: '/products?category=headphones',
        description: 'High-quality audio headsets for gaming and work',
        icon: 'Headphones',
    },
    {
        title: 'Internal Hard Drives',
        href: '/products?category=internal-hard-drive',
        description: 'Storage drives for your PC system',
        icon: 'HardDrive',
    },
    {
        title: 'Keyboards',
        href: '/products?category=keyboard',
        description: 'Mechanical and membrane keyboards for gaming and productivity',
        icon: 'Keyboard',
    },
    {
        title: 'Memory',
        href: '/products?category=memory',
        description: 'RAM modules for system performance',
        icon: 'Memory',
    },
    {
        title: 'Monitors',
        href: '/products?category=monitor',
        description: 'Displays for gaming, work, and entertainment',
        icon: 'Monitor',
    },
    {
        title: 'Motherboards',
        href: '/products?category=motherboard',
        description: 'Main circuit boards that connect all PC components',
        icon: 'CircuitBoard',
    },
    {
        title: 'Mouse',
        href: '/products?category=mouse',
        description: 'Pointing devices for gaming and productivity',
        icon: 'MousePointer',
    },
    {
        title: 'OS',
        href: '/products?category=OS',
        description: 'Operating systems for your PC setup',
        icon: 'Monitor',
    },
    {
        title: 'Power Supplies',
        href: '/products?category=power-supply',
        description: 'Power units to energize your PC components',
        icon: 'Zap',
    },
    {
        title: 'Sound Cards',
        href: '/products?category=sound-card',
        description: 'Audio processing hardware for enhanced sound quality',
        icon: 'Volume2',
    },
    {
        title: 'Thermal Paste',
        href: '/products?category=thermal-paste',
        description: 'Heat transfer compounds for CPU and GPU cooling',
        icon: 'Droplet',
    },
    {
        title: 'Video Cards',
        href: '/products?category=video-card',
        description: 'Graphics processing units for gaming and rendering',
        icon: 'Cpu',
    },
    {
        title: 'Webcams',
        href: '/products?category=webcam',
        description: 'Video cameras for streaming and video calls',
        icon: 'Video',
    },
];

export const COMPONENT_CATEGORIES = [
    'case-accessory',
    'case-fan',
    'case',
    'cpu',
    'cpu-cooler',
    'external-hard-drive',
    'fan-controller',
    'headphones',
    'internal-hard-drive',
    'keyboard',
    'memory',
    'monitor',
    'motherboard',
    'mouse',
    'OS',
    'power-supply',
    'sound-card',
    'thermal-paste',
    'video-card',
    'webcam',
];
